export const HomeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Premium Bank',
    headline: 'Unlimited Transactions with low fees',
    description: 'Access our exclusive app that allow you to make unlimited transactions with the lowest transactions',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/transaction.svg').default,
    alt: 'Transaction',
    dark: true,
    primary: true,
    darkText: false,
}

export const HomeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Unlimited Access',
    headline: 'Unlimited Access to Our Platform and Its Sevices',
    description: 'Access our exclusive app that allow you to make unlimited transactions with the lowest transactions',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/transfer.svg').default,
    alt: 'Transfer',
    dark: false,
    primary: false,
    darkText: true,
}

export const HomeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Join Us',
    headline: 'Creating an Account is Extremely Easy',
    description: 'Get Everythin set up and running in few minutes. All you need to do is add your information and you are ready to go',
    buttonLabel: 'Start Now',
    imgStart: true,
    img: require('../../images/pay.svg').default,
    alt: 'Transaction',
    dark: false,
    primary: false,
    darkText: true,
}